import { v4 as uuidv4 } from 'uuid';
export const elements = [
    {
        id: uuidv4(),
        fullName: "John Doe",
        dob: "1990-05-15",
        email: "john.doe@example.com",
        mobileNumber: "1234567890",
        roles: ["developer", "HR"],
        state: "Karnataka",
        city: "Bangalore",
    },
    {
        id: uuidv4(),
        fullName: "Jane Smith",
        dob: "1985-08-22",
        email: "jane.smith@example.com",
        mobileNumber: "9876543210",
        roles: ["developer"],
        state: "Telangana",
        city: "Hyderabad",
    },
    {
        id: uuidv4(),
        fullName: "Bob Johnson",
        dob: "1978-12-10",
        email: "bob.johnson@example.com",
        mobileNumber: "5551234567",
        roles: ["manager"],
        state: "West Bengal",
        city: "Kolkata",
    },
    {
        id: uuidv4(),
        fullName: "Alice Williams",
        dob: "1995-04-03",
        email: "alice.williams@example.com",
        mobileNumber: "1112223333",
        roles: ["developer"],
        state: "Karnataka",
        city: "Mysuru",
    },
    {
        id: uuidv4(),
        fullName: "David Smith",
        dob: "1982-11-25",
        email: "david.smith@example.com",
        mobileNumber: "5558889999",
        roles: ["designer"],
        state: "Maharashtra",
        city: "Mumbai",
    },
    {
        id: uuidv4(),
        fullName: "Emily Johnson",
        dob: "1993-07-18",
        email: "emily.johnson@example.com",
        mobileNumber: "7773331111",
        roles: ["analyst"],
        state: "Tamil Nadu",
        city: "Chennai",
    },
    {
        id: uuidv4(),
        fullName: "Michael Brown",
        dob: "1989-03-08",
        email: "michael.brown@example.com",
        mobileNumber: "4445556666",
        roles: ["manager"],
        state: "Delhi",
        city: "New Delhi",
    },
    {
        id: uuidv4(),
        fullName: "Olivia Davis",
        dob: "1998-09-12",
        email: "olivia.davis@example.com",
        mobileNumber: "6669990000",
        roles: ["HR"],
        state: "Gujarat",
        city: "Ahmedabad",
    },
    {
        id: uuidv4(),
        fullName: "William Miller",
        dob: "1975-06-30",
        email: "william.miller@example.com",
        mobileNumber: "8884442222",
        roles: ["developer"],
        state: "Rajasthan",
        city: "Jaipur",
    },
    {
        id: uuidv4(),
        fullName: "Sophia Wilson",
        dob: "1987-04-17",
        email: "sophia.wilson@example.com",
        mobileNumber: "3336667777",
        roles: ["analyst"],
        state: "Punjab",
        city: "Chandigarh",
    },
];
